/* global_inventory */
create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    gold integer null default 100,
    num_red_ml integer null default 0,
    num_green_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

/* carts */
create table
  public.carts (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    customer_name text null,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

/* carts_items */
create table
  public.carts_items (
    cart_items_id bigint generated by default as identity,
    cart_id bigint not null,
    item_sku text null,
    quantity bigint null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint carts_items_pkey primary key (cart_items_id),
    constraint carts_items_cart_id_fkey foreign key (cart_id) references carts (cart_id)
  ) tablespace pg_default;

/* catalog */
create table
  public.catalog (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sku bigint null,
    name text null,
    price bigint null,
    num_red_ml bigint null,
    num_green_ml bigint null,
    num_blue_ml bigint null,
    num_dark_ml bigint null,
    quantity bigint null,
    constraint catalog_pkey primary key (id)
  ) tablespace pg_default;

